name: MCTrilhas
version: "${project.version}"
main: com.magnocat.mctrilhas.MCTrilhasPlugin
api-version: "1.20"
author: MagnoCat
description: Plugin de trilhas e insígnias com temática escoteira para o servidor MC Trilhas.
website: https://github.com/magnocat/MCTrilhas
softdepend: [Vault, WorldGuard, PlaceholderAPI]

commands:
  scout:
    description: Comando principal do plugin de escoteiros.
    usage: "/<command> [subcommand]"
    aliases: [trilhas, insignia, escoteiro]
  daily:
    description: Coleta a recompensa diária de Totens.
    usage: /<command>
    permission: mctrilhas.daily
    aliases: [recompensa, reward]
  ranque:
    description: Mostra seu progresso para o próximo ranque escoteiro.
    usage: /<command>
    permission: mctrilhas.ranque
    aliases: [rank]
    permission-message: "§cVocê não tem permissão para usar este comando."
  tesouro:
    description: Inicia e gerencia sua caça ao tesouro.
    usage: /<command> [subcomando]
    permission: mctrilhas.tesouro
    aliases: [cacatesouro, treasure]
  ctf:
    description: Comando principal para o modo de jogo Capture a Bandeira.
    usage: /ctf <subcomando>
    aliases: [capturetheflag]
  familia:
    description: Comandos relacionados ao Portal da Família.
    usage: /<command> <subcomando>
    aliases: [family]
  duelo:
    description: Comando principal para o sistema de duelos.
    usage: /<command> <subcomando>
    aliases: [duel]
  apadrinhar:
    description: Apadrinha um novo jogador, promovendo-o para o ranque Filhote.
    usage: /<command> <jogador>
    permission: mctrilhas.apadrinhar
  regras:
    description: Mostra as regras do servidor.
    usage: /<command>
    aliases: [rules]
  terreno:
    description: Gerencia seu terreno protegido.
    usage: /terreno <subcomando>
    aliases: [land]

permissions:
  mctrilhas.*:
    description: Dá acesso a todos os comandos do MCTrilhas.
    children:
      mctrilhas.admin: true
      mctrilhas.admin.bypass: true
      mctrilhas.admin.silent-join: true
      mctrilhas.ctf.admin: true
      mctrilhas.ctf.join: true
      mctrilhas.ctf.leave: true
      mctrilhas.ctf.list: true
      mctrilhas.ctf.stuck: true
      mctrilhas.ctf.stats: true
      mctrilhas.daily: true
      mctrilhas.familia.use: true
      mctrilhas.hud: true
      mctrilhas.progress.other: true
      mctrilhas.ranque: true
      mctrilhas.scout.use: true
      mctrilhas.scout.board: true
      mctrilhas.scout.getmap: true
      mctrilhas.scout.admin: true
      mctrilhas.tesouro: true
      mctrilhas.duel.use: true
      mctrilhas.duel.challenge: true
      mctrilhas.duel.accept: true
      mctrilhas.duel.deny: true
      mctrilhas.duel.forfeit: true
      mctrilhas.duel.admin: true
      mctrilhas.duel.top: true
      mctrilhas.duel.spectate: true
      mctrilhas.duel.kits: true
      mctrilhas.duel.stats: true
      mctrilhas.duel.stats.other: true
      mctrilhas.pet.use: true
      mctrilhas.pet.summon: true
      mctrilhas.pet.release: true
      mctrilhas.pet.name: true
      mctrilhas.admin.pet: true
      mctrilhas.pet.shop: true
      mctrilhas.pet.info: true
      mctrilhas.pet.alimentar: true
      mctrilhas.admin.pet.reset: true
      mctrilhas.apadrinhar: true
      mctrilhas.land.use: true
      mctrilhas.land.claim: true
      mctrilhas.land.cost: true
      mctrilhas.land.addmember: true
      mctrilhas.land.removemember: true
      mctrilhas.land.abandon: true
      mctrilhas.land.home: true
      mctrilhas.land.setgreeting: true
      mctrilhas.land.setfarewell: true
      mctrilhas.land.sell: true
      mctrilhas.land.acceptsale: true
      mctrilhas.land.setflag: true
      mctrilhas.land.info: true
  mctrilhas.scout.use:
    description: Permite ao jogador ver suas próprias insígnias e progresso.
    default: true
  mctrilhas.scout.board:
    description: Permite ativar ou desativar o painel lateral de estatísticas.
    default: true
  mctrilhas.scout.getmap:
    description: Permite ao jogador recuperar um mapa-troféu perdido.
    default: true
  mctrilhas.daily:
    description: Permite ao jogador coletar a recompensa diária.
    default: true
  mctrilhas.ranque:
    description: Permite ao jogador ver seu progresso de ranque.
    default: true
  mctrilhas.tesouro:
    description: Permite ao jogador participar da caça ao tesouro.
    default: true
  mctrilhas.ctf.join:
    description: Permite entrar na fila do CTF.
    default: true
  mctrilhas.ctf.leave:
    description: Permite sair da fila do CTF.
    default: true
  mctrilhas.ctf.list:
    description: Permite listar as arenas de CTF.
    default: true
  mctrilhas.ctf.stuck:
    description: Permite que um jogador se mate se ficar preso em uma partida de CTF.
    default: true
  mctrilhas.ctf.stats:
    description: Permite ver as próprias estatísticas de CTF.
    default: true
  mctrilhas.ctf.stats.other:
    description: Permite ver as estatísticas de CTF de outros jogadores.
    default: op
  mctrilhas.familia.use:
    description: Permite usar os comandos do Portal da Família.
    default: true
  mctrilhas.hud:
    description: Permite ativar ou desativar o HUD de estatísticas.
    default: true
  mctrilhas.ctf.admin:
    description: Permite gerenciar as arenas de CTF.
    default: op
  mctrilhas.admin:
    description: Permissão principal para acesso a comandos administrativos.
    default: op
  mctrilhas.scout.admin:
    description: Permite acesso aos comandos administrativos, como remover insígnias.
    default: op
  mctrilhas.progress.other:
    description: Permite ver o progresso de outros jogadores.
    default: op
  mctrilhas.admin.silent-join:
    description: Permite que o jogador entre e saia do servidor silenciosamente.
    default: op
  mctrilhas.admin.bypass:
    description: Permite que o jogador ignore o bloqueador de comandos.
    default: op
  mctrilhas.duel.use:
    description: Permite usar os comandos básicos do sistema de duelos.
    default: true
  mctrilhas.duel.challenge:
    description: Permite desafiar outros jogadores para um duelo.
    default: true
  mctrilhas.duel.accept:
    description: Permite aceitar um desafio de duelo.
    default: true
  mctrilhas.duel.deny:
    description: Permite negar um desafio de duelo.
    default: true
  mctrilhas.duel.forfeit:
    description: Permite desistir de um duelo em andamento.
    default: true
  mctrilhas.duel.admin:
    description: Permite criar e gerenciar arenas de duelo.
    default: op
  mctrilhas.duel.kits:
    description: Permite visualizar os kits de duelo disponíveis.
    default: true
  mctrilhas.duel.stats:
    description: Permite visualizar as próprias estatísticas de duelo.
    default: true
  mctrilhas.duel.stats.other:
    description: Permite visualizar as estatísticas de duelo de outros jogadores.
    default: op
  mctrilhas.duel.top:
    description: Permite visualizar o ranking de ELO dos duelistas.
    default: true
  mctrilhas.duel.spectate:
    description: Permite assistir a duelos em andamento.
    default: true
  mctrilhas.pet.use:
    description: Permite usar os comandos básicos do sistema de pets.
    default: true
  mctrilhas.pet.summon:
    description: Permite invocar um pet.
    default: true
  mctrilhas.pet.release:
    description: Permite guardar (liberar) seu pet.
    default: true
  mctrilhas.pet.name:
    description: Permite nomear seu pet.
    default: true
  mctrilhas.pet.shop:
    description: Permite abrir a loja para adquirir um pet.
    default: true
  mctrilhas.pet.info:
    description: Permite ver as estatísticas do seu pet.
    default: true
  mctrilhas.pet.alimentar:
    description: Permite alimentar seu pet para aumentar a felicidade dele.
    default: true
  mctrilhas.admin.pet:
    description: Permite acesso aos comandos de administração de pets.
    default: op
  mctrilhas.admin.pet.reset:
    description: Permite resetar os dados de pet de um jogador.
    default: op
  mctrilhas.apadrinhar:
    description: Permite que um jogador apadrinhe um novo membro.
    default: true
  mctrilhas.land.use:
    description: Permite usar os comandos básicos de terreno.
    default: true
  mctrilhas.land.claim:
    description: Permite reivindicar um terreno.
    default: true
  mctrilhas.land.cost:
    description: Permite ver o custo de uma seleção de terreno.
    default: true
  mctrilhas.land.addmember:
    description: Permite adicionar um amigo ao seu terreno.
    default: true
  mctrilhas.land.removemember:
    description: Permite remover um amigo do seu terreno.
    default: true
  mctrilhas.land.info:
    description: Permite ver informações sobre seu terreno.
    default: true
  mctrilhas.land.sethome:
    description: Permite definir o ponto de teletransporte do seu terreno.
    default: true
  mctrilhas.land.setgreeting:
    description: Permite definir a mensagem de boas-vindas do seu terreno.
    default: true
  mctrilhas.land.setfarewell:
    description: Permite definir a mensagem de despedida do seu terreno.
    default: true
  mctrilhas.land.sell:
    description: Permite colocar seu terreno à venda para outro jogador.
    default: true
  mctrilhas.land.acceptsale:
    description: Permite aceitar uma oferta de compra de terreno.
    default: true
  mctrilhas.land.setflag:
    description: Permite alterar as permissões (flags) do seu terreno.
    default: true
  mctrilhas.land.abandon:
    description: Permite abandonar um terreno protegido.
    default: true
