name: MCTrilhas
version: '${project.version}'
main: com.magnocat.mctrilhas.MCTrilhasPlugin
api-version: '1.20'
author: MagnoCat
description: Plugin de trilhas e insígnias com temática escoteira para o servidor MC Trilhas.
website: https://github.com/magnocat/MCTrilhas
softdepend: [Vault, WorldGuard, PlaceholderAPI]

commands:
  scout:
    description: Comando principal do plugin de escoteiros.
    usage: "/<command> [subcommand]"
    aliases: [trilhas, insignia, escoteiro]
  daily:
    description: Coleta a recompensa diária de Totens.
    usage: /<command>
    permission: mctrilhas.daily
    aliases: [recompensa, reward]
  ranque:
    description: Mostra seu progresso para o próximo ranque escoteiro.
    usage: /<command>
    permission: mctrilhas.ranque
    aliases: [rank]
    permission-message: "§cVocê não tem permissão para usar este comando."
  tesouro:
    description: Inicia e gerencia sua caça ao tesouro.
    usage: /<command> [subcomando]
    permission: mctrilhas.tesouro
    aliases: [cacatesouro, treasure]
  ctf:
    description: Comando principal para o modo de jogo Capture a Bandeira.
    usage: /ctf <subcomando>
    aliases: [capturetheflag]
    permission: mctrilhas.ctf.use

permissions:
  mctrilhas.*:
    description: Dá acesso a todos os comandos do MCTrilhas.
    children:
      mctrilhas.scout.use: true
      mctrilhas.daily: true
      mctrilhas.admin: true
      mctrilhas.scout.getmap: true
      mctrilhas.ranque: true
      mctrilhas.progress.other: true
      mctrilhas.tesouro: true
      mctrilhas.ctf.use: true
      mctrilhas.ctf.join: true
      mctrilhas.ctf.leave: true
      mctrilhas.ctf.list: true
      mctrilhas.ctf.stats: true
      mctrilhas.ctf.stats.other: true
      mctrilhas.ctf.admin: true
  mctrilhas.scout.use:
    description: Permite ao jogador ver suas próprias insígnias e progresso.
    default: true
  mctrilhas.scout.getmap:
    description: Permite ao jogador recuperar um mapa-troféu perdido.
    default: true
  mctrilhas.daily:
    description: Permite ao jogador coletar a recompensa diária.
    default: true
  mctrilhas.ranque:
    description: Permite ao jogador ver seu progresso de ranque.
    default: true
  mctrilhas.tesouro:
    description: Permite ao jogador participar da caça ao tesouro.
    default: true
  mctrilhas.ctf.use:
    description: Permite usar os comandos básicos do CTF.
    default: true
  mctrilhas.ctf.join:
    description: Permite entrar na fila do CTF.
    default: true
  mctrilhas.ctf.leave:
    description: Permite sair da fila do CTF.
    default: true
  mctrilhas.ctf.list:
    description: Permite listar as arenas de CTF.
    default: true
  mctrilhas.ctf.stats:
    description: Permite ver as próprias estatísticas de CTF.
    default: true
  mctrilhas.ctf.stats.other:
    description: Permite ver as estatísticas de CTF de outros jogadores.
    default: op
  mctrilhas.ctf.admin:
    description: Permite gerenciar as arenas de CTF.
    default: op
  mctrilhas.admin:
    description: Permite acesso aos comandos administrativos, como remover insígnias.
    default: op
  mctrilhas.progress.other:
    description: Permite ver o progresso de outros jogadores.
    default: op