name: GodMode-MCtrilhas
version: '${project.version}'
authors: [MagnoCat]
main: com.magnocat.godmode.GodModePlugin
api-version: 1.21
description: Plugin para o servidor MC Trilhas com temática escoteira
softdepend: [Vault, WorldGuard]
commands:
  scout:
    description: Comandos do sistema escoteiro
    usage: /<command> [subcomando]
permissions:
  godmode.scout.use:
    description: Permite usar comandos do sistema escoteiro
    default: true
